### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by abdhalees** [FACG2/Fac-Community#2]
- [x] connect sign in with passport (1h) https://github.com/FACG2/Fac-Community/issues/14

- [x] check if the user already exists or not (15m) 

- [x] check if the user is a FAC member (15m)

- [x] add the user to the database (15m)

- [x] testing (1h)

- [x] styling (2h) https://github.com/FACG2/Fac-Community/issues/36
![21850636_489538558073582_838806993_n](https://user-images.githubusercontent.com/26231211/30536154-666d29c4-9c6d-11e7-8275-4fc6c09b195f.jpg)
