### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by abdhalees** [FACG2/Fac-Community#5]
- [x] decide how to filter (15m)

- [x] get data from database(1h) https://github.com/FACG2/Fac-Community/issues/44

- [x] get data by filters(1h) https://github.com/FACG2/Fac-Community/issues/44

- [x] testing(1h)

- [x] styling(1d) https://github.com/FACG2/Fac-Community/issues/53
 
![21641303_489538541406917_1220185587_n](https://user-images.githubusercontent.com/26231211/30536333-12858d14-9c6e-11e7-9846-da25d4355448.jpg)
